"use client";

import { CopyButton } from "@/components/CopyButton";

const BADGE_TYPES: { type: "version" | "downloads" | "stars" | "rating"; label: string }[] = [
  { type: "version", label: "Version" },
  { type: "downloads", label: "Downloads" },
  { type: "stars", label: "Stars" },
  { type: "rating", label: "Rating" },
];

/** README-ready markdown for every badge type on one package, each with a live
 *  preview and a copy button. `siteUrl` is passed in rather than computed here
 *  (this is a client component; `siteUrl()` reads server env vars). */
export function BadgeSnippet({
  owner,
  name,
  siteUrl,
}: {
  owner: string;
  name: string;
  siteUrl: string;
}) {
  const packageUrl = `${siteUrl}/p/${owner}/${name}`;

  return (
    <div className="flex flex-col gap-2">
      {BADGE_TYPES.map(({ type, label }) => {
        const badgeUrl = `${siteUrl}/api/v1/packages/${owner}/${name}/badge?type=${type}`;
        const markdown = `[![${label.toLowerCase()}](${badgeUrl})](${packageUrl})`;
        return (
          <div
            key={type}
            className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-border bg-bg-elevated px-3 py-2"
          >
            <div className="flex min-w-0 items-center gap-3">
              {/* eslint-disable-next-line @next/next/no-img-element -- remote SVG generated by our own badge route, not an optimizable local asset */}
              <img src={badgeUrl} alt={`${label} badge`} className="h-5 shrink-0" />
              <code className="min-w-0 overflow-x-auto whitespace-pre text-xs text-fg-muted">
                {markdown}
              </code>
            </div>
            <CopyButton value={markdown} label="Copy" />
          </div>
        );
      })}
    </div>
  );
}
